BrowserCategory["AbstractAlgebra", None,
  { 
 
  Item["Contents","Contents.nb",CopyTag->"Contents"],
Item[Delimiter],
   (*IntroductionGuide.nb Categories*)
 BrowserCategory["Introduction to AbstractAlgebra",None,
{Item["READ ME FIRST","Guide1.nb",CopyTag->"First"],
Item["Contents","Contents.nb",CopyTag->"IntroContents"],
Item[Delimiter],
Item["Introduction to AbstractAlgebra","Guide1.nb",CopyTag->"Intro"],
Item["Packages in AbstractAlgebra","Guide1.nb",CopyTag->"Packages"],
 BrowserCategory["Basic Structures",None,
 {Item["Overview of Structures","Guide1.nb",CopyTag->"Structures"],
  Item["How to form Structures","Guide1.nb",CopyTag->"Form"]}],
Item["How to use a Mode","Guide1.nb",CopyTag->"Mode"],
Item["Visual mode with large elements","Guide1.nb",CopyTag->"Visual"],
Item["Changing the DefaultStructure","Guide1.nb",CopyTag->"How"]}],


  (*Insert Groupoid Categories here *)
  
BrowserCategory["Groupoids",None,
{Item["Groupoids-READ ME FIRST","Guide2A.nb",CopyTag->"First"],
Item["Contents","Contents.nb",CopyTag->"GroupoidsContents"],
Item[Delimiter],
BrowserCategory["Forming Groupoids",None,
{
Item["FormGroupoid","Guide2A.nb",CopyTag->"FormGroupoid"],
Item["GenerateGroupoid","Guide2A.nb",CopyTag->"GenerateGroupoid"],
Item["FormGroupoidByTable","Guide2A.nb",CopyTag->"FormGroupoidByTable"],
Item["FormGroupoidFromCycles and RandomGroupoid","Guide2A.nb",CopyTag->"OtherForm"],
Item["GenerateGroupoidByRelations and FormGroupoidByRelations","GenerateByRelations.nb",CopyTag->"Relations"]}],

Item["Structure of Groupoids","Guide2A.nb",CopyTag->"Structure"],

BrowserCategory["Testing properties of a group",None,
{Item["The four standard functions","Guide2A.nb",CopyTag->"FourStandard"],
Item["Related functions","Guide2A.nb",CopyTag->"Related"]}],

BrowserCategory["Built-in groupoids",None,
{Item["Groupoids based on the integers mod n","Guide2B.nb",CopyTag->"Integers"],
Item["Other numeric groupoids","Guide2B.nb",CopyTag->"OtherNum"],
Item["Groups of permutations","Guide2B.nb",CopyTag->"Permutations"],
Item["Dihedral and Cyclic groups","Guide2B.nb",CopyTag->"Dihedral"],
Item["Other groupoids","Guide2B.nb",CopyTag->"OtherGroupoids"]}],

Item["Cayley tables","Guide2B.nb",CopyTag->"Cayley"],

BrowserCategory["Building other structures",None,
{Item["StructureIntroduction","Guide2C.nb",CopyTag->"ThreeQuestions"],
Item["Direct products","Guide2C.nb",CopyTag->"DirectProducts"],
Item["Subgroups","Guide2C.nb",CopyTag->"Subgroups"],
Item["Quotient groups","Guide2C.nb",CopyTag->"Quotients"]}],

Item["Other group properties","Guide2D.nb",CopyTag->"OtherProps"]
}],
  
 (*Insert Ringoid Categories here *)
 
BrowserCategory["Ringoids",None,
{Item["Ringoids-READ ME FIRST","Guide3A.nb",CopyTag->"First"],
Item["Contents","Contents.nb",CopyTag->"RingoidContents"],
Item[Delimiter],
BrowserCategory["Forming Ringoids",None,
{Item["FormRingoid","Guide3A.nb",CopyTag->"FormRingoid"],
Item["FormRingoidByTable","Guide3A.nb",CopyTag->"FormRingoidByT"]}],

BrowserCategory["Structure of Ringoids",None,
{Item["Basic functions","Guide3A.nb",CopyTag->"BasicRingoid"],
Item["Ring related functions","Guide3A.nb",CopyTag->"RelatedRingoid"],
Item["Groupoids from ringoids","Guide3A.nb",CopyTag->"GroupoidsFromR"]}],

BrowserCategory["Testing Ring Properties",None,
{Item["Additive properties","Guide3A.nb",CopyTag->"AdditiveP"],
Item["Multiplicative properties","Guide3A.nb",CopyTag->"MultiplicativeP"],
Item["Distributive property","Guide3A.nb",CopyTag->"DistributiveP"],
Item["RingQ test","Guide3A.nb",CopyTag->"RingQ"],
Item["Specialized rings","Guide3A.nb",CopyTag->"SpecializedRings"],
Item["Closure of subsets","Guide3A.nb",CopyTag->"Closure"],
Item["Testing other properties","Guide3A.nb",CopyTag->"TestingOther"]}],

BrowserCategory["Built-in Ringoids",None,
{Item["Numeric Rings","Guide3A.nb",CopyTag->"NumericRings"],
Item["Other Rings","Guide3A.nb",CopyTag->"OtherRings"]}],
Item["Using Cayley tables ","Guide3B.nb",CopyTag->"Cayley"],

BrowserCategory["Building other structures",None,
{Item["Direct products of rings","Guide3B.nb",CopyTag->"DirectProducts"],
Item["Subrings and ideals","Guide3B.nb",CopyTag->"Subrings"],
Item["Quotient Rings","Guide3B.nb",CopyTag->"QuotientRings"]}],

Item["Extension ringoids","Guide3B.nb",CopyTag->"ExtensionRings"],

BrowserCategory["Polynomials over a ringoid",None,
{Item["Forming polynomials","Guide3B.nb",CopyTag->"FormingPolynomials"],
Item["Random polynomials","Guide3B.nb",CopyTag->"RandomPolynomials"],
Item["Polynomial arithmetic","Guide3B.nb",CopyTag->"PolynomialArith"],
Item["Polynomial Quotient Rings","Guide3B.nb",CopyTag->"QuotientPolynomials"],
Item["Irreducibility of Polynomials","Guide3B.nb",CopyTag->"Irreducibility"],
Item["Solving Equations, Evaluation","Guide3B.nb",CopyTag->"FunctionsSolving"],
Item["Extensions of Stnrd Mathematica","Guide3B.nb",CopyTag->"ExtensionsOfOrdinary"],
Item["Miscellaneous functions","Guide3B.nb",CopyTag->"MiscPoly"]}],

BrowserCategory["Matrices over a ringoid",None,
{Item["MatricesOver","Guide3B.nb",CopyTag->"MatricesOver"],
Item["Individual matrices","Guide3B.nb",CopyTag->"IndividualMatrices"],
Item["Matrix arithmetic","Guide3B.nb",CopyTag->"MatrixArithmetic"],
Item["Determinants & inverses","Guide3B.nb",CopyTag->"Determinants"],
Item["Matrix ringoids","Guide3B.nb",CopyTag->"MatrixRingoids"],
Item["Matrix groupoids","Guide3B.nb",CopyTag->"MatrixGroupoids"],
Item["Miscellaneous matrix functions","Guide3B.nb",CopyTag->"MiscMatFunctions"]}],

BrowserCategory["Functions over Ringoids",None,
{Item["Function Extensions","Guide3B.nb",CopyTag->"FunctionsOverElements"],
Item["Function Arithmetic","Guide3B.nb",CopyTag->"FunctionArith"],
Item["Polynomial Conversion, Interpolation","Guide3B.nb",CopyTag->"PolyConversion"]}],

Item["Finite fields","Guide3B.nb",CopyTag->"FiniteFields"]
}],  
  
BrowserCategory["Morphoids",None,
{Item["Morphoids-READ ME FIRST","Guide4.nb",CopyTag->"First"],
Item["Contents","Contents.nb",CopyTag->"MorphoidContents"],
Item[Delimiter],
Item["Introduction","Guide4.nb",CopyTag->"What"],
Item["Forming Morphoids","Guide4.nb",CopyTag->"Form"],
Item["The structure of Morphoids","Guide4.nb",CopyTag->"Structure"],
Item["Built-in Morphoids","Guide4.nb",CopyTag->"BuiltIn"],
BrowserCategory["Properties",None,
{Item["Surjectivity and injectivity","Guide4.nb",
	CopyTag->"SurjectivityInjectivity"],
Item["Preserving Operations","Guide4.nb",CopyTag->"PreservingOperations"]}],
Item["Kernel, Image, and InverseImage(s)","Guide4.nb",CopyTag->"Kernel"],
Item["Automorphisms","Guide4.nb",CopyTag->"Automorphisms"],
Item["Visualizing Morphoids","Guide4.nb",CopyTag->"Visual"]
}],  
 
BrowserCategory["Additional functionality",None,
{Item["Additional-READ ME FIRST","Guide5.nb",CopyTag->"First"],
Item["Contents","Contents.nb",CopyTag->"AdditionalContents"],
Item[Delimiter],
Item["Global variables and options","Guide5.nb",CopyTag->"Global"],

BrowserCategory["Permutations and Cycles",None,
{Item["Introduction to Permutations","Guide5.nb",CopyTag->"PermIntroduction"],
Item["Permutation operations","Guide5.nb",CopyTag->"PermOperations"],
Item["Representing permutations","Guide5.nb",CopyTag->"PermRepresent"],
Item["Cycles","Guide5.nb",CopyTag->"Cycles"],
Item["Cycle operations","Guide5.nb",CopyTag->"CycleOperations"],
Item["Other cycle-related functions","Guide5.nb",CopyTag->"OtherCycle"],
Item["Stabilizers and orbits","Guide5.nb",CopyTag->"Stabilizers"]}],
BrowserCategory["Z[Sqrt[d]]",None,
{Item["Basic Zd functions","Guide5.nb",CopyTag->"BasicZ"],
Item["Divisibility","Guide5.nb",CopyTag->"DivisibilityZ"],
Item["Norm-related functions","Guide5.nb",CopyTag->"NormZ"]}],
BrowserCategory["Miscellaneous functions",None,
{Item["Working with lists","Guide5.nb",CopyTag->"WorkLists"],
Item["Working with graphics","Guide5.nb",CopyTag->"WorkGraphics"],
Item["Adjoin","Guide5.nb",CopyTag->"Adjoin"],
Item["Disguising groups and rings","Guide5.nb",CopyTag->"Disguising"],
Item["A look at some functions in LabCode","Guide5.nb",CopyTag->"LabCode"],
Item["Potpourri","Guide5.nb",CopyTag->"Potpourri"]}]
}],

BrowserCategory["Appendices",None,
{Item["Contents","Contents.nb",CopyTag->"AppendicesContents"],
Item[Delimiter],
BrowserCategory["Appendix A - Installation Instructions",None,
{Item["Install-Version 2.x under Windows","Appendices.nb",CopyTag->"install2w"],
Item["Install-Version 2.x under other platforms","Appendices.nb",CopyTag->"install2o"],
Item["Install-Version 3.0 or higher","Appendices.nb",CopyTag->"install3"],
Item["Install-from WWW page","Appendices.nb",CopyTag->"installFromWeb"]}],
Item["Appendix A - Relevant References","Appendices.nb",CopyTag->"MathematicaRefs"],
BrowserCategory["Objects in AbstractAlgebra",None,
{Item["Alphabetically","Appendices.nb",CopyTag->"alpha"],
Item["By Packages","Appendices.nb",CopyTag->"pack"],
Item["Extended from standard","Appendices.nb",CopyTag->"ext"],
Item["Usage statements--alphabetically","Appendices.nb",CopyTag->"usagealpha"],
Item["Usage statements--by packages","Appendices.nb",CopyTag->"usagepackages"]}],
Item["Appendix B - Lab 0","Appendices.nb",CopyTag->"Lab0"]
}],

Item[Delimiter],

BrowserCategory["EAAM Info",None,
{Item["Contents","Contents.nb",CopyTag->"EAAMInfoContents"],
Item[Delimiter],
Item["Overview of EAAM","EAAMInfo.nb",CopyTag->"overview"],
Item["Summaries of group labs","EAAMInfo.nb",CopyTag->"grplb"],
BrowserCategory["Contents of group labs",None,
{Item["READ FIRST - Grp Lab Contents","EAAMInfo.nb",CopyTag->"gtoc0"],
Item["Cont. Group Lab 1","EAAMInfo.nb",CopyTag->"gtoc1"],
Item["Cont. Group Lab 2","EAAMInfo.nb",CopyTag->"gtoc2"],
Item["Cont. Group Lab 3","EAAMInfo.nb",CopyTag->"gtoc3"],
Item["Cont. Group Lab 4","EAAMInfo.nb",CopyTag->"gtoc4"],
Item["Cont. Group Lab 5","EAAMInfo.nb",CopyTag->"gtoc5"],
Item["Cont. Group Lab 6","EAAMInfo.nb",CopyTag->"gtoc6"],
Item["Cont. Group Lab 7","EAAMInfo.nb",CopyTag->"gtoc7"],
Item["Cont. Group Lab 8","EAAMInfo.nb",CopyTag->"gtoc8"],
Item["Cont. Group Lab 9","EAAMInfo.nb",CopyTag->"gtoc9"],
Item["Cont. Group Lab 10","EAAMInfo.nb",CopyTag->"gtoc10"],
Item["Cont. Group Lab 11","EAAMInfo.nb",CopyTag->"gtoc11"],
Item["Cont. Group Lab 12","EAAMInfo.nb",CopyTag->"gtoc12"],
Item["Cont. Group Lab 13","EAAMInfo.nb",CopyTag->"gtoc13"],
Item["Cont. Group Lab 14","EAAMInfo.nb",CopyTag->"gtoc14"]}],
Item["Summaries of ring labs","EAAMInfo.nb",CopyTag->"rnglb"],
BrowserCategory["Contents of ring labs",None,
{Item["READ FIRST - Rng Lab Contents","EAAMInfo.nb",CopyTag->"rtoc0"],
Item["Cont. Ring Lab 1","EAAMInfo.nb",CopyTag->"rtoc1"],
Item["Cont. Ring Lab 2","EAAMInfo.nb",CopyTag->"rtoc2"],
Item["Cont. Ring Lab 3","EAAMInfo.nb",CopyTag->"rtoc3"],
Item["Cont. Ring Lab 4","EAAMInfo.nb",CopyTag->"rtoc4"],
Item["Cont. Ring Lab 5","EAAMInfo.nb",CopyTag->"rtoc5"],
Item["Cont. Ring Lab 6","EAAMInfo.nb",CopyTag->"rtoc6"],
Item["Cont. Ring Lab 7","EAAMInfo.nb",CopyTag->"rtoc7"],
Item["Cont. Ring Lab 8","EAAMInfo.nb",CopyTag->"rtoc8"],
Item["Cont. Ring Lab 9","EAAMInfo.nb",CopyTag->"rtoc9"],
Item["Cont. Ring Lab 10","EAAMInfo.nb",CopyTag->"rtoc10"],
Item["Cont. Ring Lab 11","EAAMInfo.nb",CopyTag->"rtoc11"],
Item["Cont. Ring Lab 12","EAAMInfo.nb",CopyTag->"rtoc12"],
Item["Cont. Ring Lab 13","EAAMInfo.nb",CopyTag->"rtoc13"]}],
BrowserCategory["Palettes for EAAM",None,
{Item["Palette introduction-READ ME","EAAMInfo.nb",
	CopyTag->"palintro"],
Item["AbstractAlgebra","EAAMInfo.nb", CopyTag->"AbstractAlgebraPalette"],
Item["Palette Help","EAAMInfo.nb",CopyTag->"PaletteHelp"],
Item["Groupoids","EAAMInfo.nb",CopyTag->"GroupoidsPalette"],
Item["Ringoids and Morphoids","EAAMInfo.nb",CopyTag->"RingoidsPalette"],
Item["General AbstractAlgebra functions","EAAMInfo.nb",
	CopyTag->"GeneralPalette"],
Item["Group functions","EAAMInfo.nb",CopyTag->"GroupPalette"],
Item["Permutation functions","EAAMInfo.nb",CopyTag->"PermutationPalette"],
Item["Morphism functions","EAAMInfo.nb",CopyTag->"MorphismPalette"],
Item["Ring functions","EAAMInfo.nb",CopyTag->"RingPalette"],
Item["Polynomial functions","EAAMInfo.nb",CopyTag->"PolynomialPalette"],
Item["Matrix functions","EAAMInfo.nb",CopyTag->"MatrixPalette"],
Item["Galois field functions","EAAMInfo.nb",CopyTag->"GaloisPalette"],
Item["Z[Sqrt[d]] functions","EAAMInfo.nb",CopyTag->"ZdPalette"],
Item["Group (ring) properties","EAAMInfo.nb",CopyTag->"MultiPalette"],
Item["GroupCalculator","EAAMInfo.nb",CopyTag->"GroupCalculator"],
Item["All AbstractAlgebra functions","EAAMInfo.nb",CopyTag->"AllPalette"],
Item["Group Lab Two","EAAMInfo.nb",CopyTag->"GLab2Palette"],
Item["Setting up Morphoids","EAAMInfo.nb",CopyTag->"MorphoidPalette"]}],
BrowserCategory["Preface",None,
{
Item["What is EAAM?","EAAMInfo.nb",CopyTag->"What is EAAM?"],
Item["More about AbstractAlgebra","EAAMInfo.nb",CopyTag->"More about AbstractAlgebra"],
Item["More about the labs","EAAMInfo.nb",CopyTag->"More about labs"],
Item["Acknowledgements","EAAMInfo.nb",CopyTag->"Acknowledgements"]}],
Item["EAAM Table of Contents","EAAMInfo.nb",CopyTag->"EAAM TOC"]
}],

BrowserCategory["EAAM Labs",None,{
	Item["Labs-READ ME first","Labs.nb",CopyTag->"standAlone"],
	Item[Delimiter],
	Item["Lab0 (Intro to Mathematica)-Stand Alone","Labs.nb",CopyTag->"SALab0"],
	Item["Group Labs-Stand Alone","Labs.nb",CopyTag->"SAGroupLabs"],
	Item["Ring Labs-Stand Alone","Labs.nb",CopyTag->"SARingLabs"],
Item[Delimiter],
Item["Lab0 (Intro to Mathematica)-In Browser",
	FrontEnd`FileName[ {ParentDirectory[ParentDirectory[ ]], 
	"Lab0"}, "EAAMLab0.nb"],CopyTag->"Lab0"],
BrowserCategory["Group Labs-In Browser",None,{Item["Brws. Group Lab 1", 
	FrontEnd`FileName[ {ParentDirectory[ParentDirectory[ ]], 
	"GroupLabs"}, "GrpLab01.nb"], CopyTag->"GL1"],
	Item["Brws. Group Lab 2", 
	FrontEnd`FileName[ {ParentDirectory[ParentDirectory[ ]], 
	"GroupLabs"}, "GrpLab02.nb"], CopyTag->"GL2"],
	Item["Brws. Group Lab 3", 
	FrontEnd`FileName[ {ParentDirectory[ParentDirectory[ ]], 
	"GroupLabs"}, "GrpLab03.nb"], CopyTag->"GL3"],
	Item["Brws. Group Lab 4", 
	FrontEnd`FileName[ {ParentDirectory[ParentDirectory[ ]], 
	"GroupLabs"}, "GrpLab04.nb"], CopyTag->"GL4"],
	Item["Brws. Group Lab 5", 
	FrontEnd`FileName[ {ParentDirectory[ParentDirectory[ ]], 
	"GroupLabs"}, "GrpLab05.nb"], CopyTag->"GL5"],
	Item["Brws. Group Lab 6", 
	FrontEnd`FileName[ {ParentDirectory[ParentDirectory[ ]], 
	"GroupLabs"}, "GrpLab06.nb"], CopyTag->"GL6"],
	Item["Brws. Group Lab 7", 
	FrontEnd`FileName[ {ParentDirectory[ParentDirectory[ ]], 
	"GroupLabs"}, "GrpLab07.nb"], CopyTag->"GL7"],
	Item["Brws. Group Lab 8", 
	FrontEnd`FileName[ {ParentDirectory[ParentDirectory[ ]], 
	"GroupLabs"}, "GrpLab08.nb"], CopyTag->"GL8"],
	Item["Brws. Group Lab 9", 
	FrontEnd`FileName[ {ParentDirectory[ParentDirectory[ ]], 
	"GroupLabs"}, "GrpLab09.nb"], CopyTag->"GL9"],
	Item["Brws. Group Lab 10", 
	FrontEnd`FileName[ {ParentDirectory[ParentDirectory[ ]], 
	"GroupLabs"}, "GrpLab10.nb"], CopyTag->"GL10"],
	Item["Brws. Group Lab 11", 
	FrontEnd`FileName[ {ParentDirectory[ParentDirectory[ ]], 
	"GroupLabs"}, "GrpLab11.nb"], CopyTag->"GL11"],
	Item["Brws. Group Lab 12", 
	FrontEnd`FileName[ {ParentDirectory[ParentDirectory[ ]], 
	"GroupLabs"}, "GrpLab12.nb"], CopyTag->"GL12"],
	Item["Brws. Group Lab 13", 
	FrontEnd`FileName[ {ParentDirectory[ParentDirectory[ ]], 
	"GroupLabs"}, "GrpLab13.nb"], CopyTag->"GL13"],
	Item["Brws. Group Lab 14", 
	FrontEnd`FileName[ {ParentDirectory[ParentDirectory[ ]], 
	"GroupLabs"}, "GrpLab14.nb"], CopyTag->"GL14"]}],
	
BrowserCategory["Ring Labs-In Browser",None,{Item["Brws. Ring Lab 1", 
	FrontEnd`FileName[ {ParentDirectory[ParentDirectory[ ]], 
	"RingLabs"}, "RngLab01.nb"], CopyTag->"RL1"],
	Item["Brws. Ring Lab 2", 
	FrontEnd`FileName[ {ParentDirectory[ParentDirectory[ ]], 
	"RingLabs"}, "RngLab02.nb"], CopyTag->"RL2"],
	Item["Brws. Ring Lab 3", 
	FrontEnd`FileName[ {ParentDirectory[ParentDirectory[ ]], 
	"RingLabs"}, "RngLab03.nb"], CopyTag->"RL3"],
	Item["Brws. Ring Lab 4", 
	FrontEnd`FileName[ {ParentDirectory[ParentDirectory[ ]], 
	"RingLabs"}, "RngLab04.nb"], CopyTag->"RL4"],
	Item["Brws. Ring Lab 5", 
	FrontEnd`FileName[ {ParentDirectory[ParentDirectory[ ]], 
	"RingLabs"}, "RngLab05.nb"], CopyTag->"RL5"],
	Item["Brws. Ring Lab 6", 
	FrontEnd`FileName[ {ParentDirectory[ParentDirectory[ ]], 
	"RingLabs"}, "RngLab06.nb"], CopyTag->"RL6"],
	Item["Brws. Ring Lab 7", 
	FrontEnd`FileName[ {ParentDirectory[ParentDirectory[ ]], 
	"RingLabs"}, "RngLab07.nb"], CopyTag->"RL7"],
	Item["Brws. Ring Lab 8", 
	FrontEnd`FileName[ {ParentDirectory[ParentDirectory[ ]], 
	"RingLabs"}, "RngLab08.nb"], CopyTag->"RL8"],
	Item["Brws. Ring Lab 9", 
	FrontEnd`FileName[ {ParentDirectory[ParentDirectory[ ]], 
	"RingLabs"}, "RngLab09.nb"], CopyTag->"RL9"],
	Item["Brws. Ring Lab 10", 
	FrontEnd`FileName[ {ParentDirectory[ParentDirectory[ ]], 
	"RingLabs"}, "RngLab10.nb"], CopyTag->"RL10"],
	Item["Brws. Ring Lab 11", 
	FrontEnd`FileName[ {ParentDirectory[ParentDirectory[ ]], 
	"RingLabs"}, "RngLab11.nb"], CopyTag->"RL11"],
	Item["Brws. Ring Lab 12", 
	FrontEnd`FileName[ {ParentDirectory[ParentDirectory[ ]], 
	"RingLabs"}, "RngLab12.nb"], CopyTag->"RL12"],
	Item["Brws. Ring Lab 13", 
	FrontEnd`FileName[ {ParentDirectory[ParentDirectory[ ]], 
	"RingLabs"}, "RngLab13.nb"], CopyTag->"RL13"]}],
	
	Item[Delimiter],
	Item["Lab 0 Questions-Stand Alone","Labs.nb",CopyTag->"Quest0"],
	Item["Group Lab Questions-Stand Alone","Labs.nb",CopyTag->"QuestGL"],
	Item["Ring Lab Questions-Stand Alone","Labs.nb",CopyTag->"QuestRL"]}]

}]
